后续补充np.ma相关内容

<center><h1>Numpy Reference</h1></center>

# 1 Array object
---
## 1.1 The N-dimensional array(`ndarray`)
---

In [4]:
import numpy as np
a = np.reshape(np.arange(24), (4,6))
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

### 1.1.1 Array attributes
---

> ### Memory layout

---

In [14]:
a.flags   # information about the memory layout of the array.
a.shape   # tuple of array dimensions.
a.strides # tuple of bytes in each dimension when traversing an array.
a.ndim    # number of array dimensions.
a.data    # python buffer object pointing to the start of the array's data.
a.size    # number of elements in the array.
a.itemsize # length of one array element in bytes
a.nbytes  # total bytes consumed by the elements of the array.
a.base    # base object if memory is from some other object.
a.base is None

False

> ### Data type

---

> ### Other attributes

---

In [20]:
a.T      # self.transpose()
a.real   # the real part of array.
a.imag   # the imaginary part of array.
a.flat   # 1-D iterator over the array
a.ctypes # an object to simplif the interaction of the array with the ctype module.

### 1.1.2 Array methods
---

In [206]:
a = np.arange(24, 0, -1).reshape(4, 6)
print(a)
a.all() # False
a.any() # True
a.argmax() # 23
a.argmin() # 0
a.argpartition(2) # 见下面注释 
a.argsort(axis=0) # 索引列排序
a.argsort()

# a的第三行第一个，第二行第二个，第四行第三个，第一行第四个，．．．
# 4x6 * 6x1 = 4x1
np.choose([2,1,3,0,2,2],a) # array([12, 17,  4, 21,  8,  7])

# 限定元素的取值范围，比3小取3,比６大取6
a.clip(3,6) 

# numpy.compress(condition, a, axis=None, out=None)
a.compress((True,False,True), axis=0) #

# numpy.copy(a, order='K')
a.copy()

# numpy.cumprod(a, axis=None, dtype=None, out=None)
# Return the cumulative product of elements along a given axis.
a.cumprod()

# numpy.cumsum(a, axis=None, dtype=None, out=None)
# Return the cumulative sum of the elements along a given axis.
a.cumsum()

# numpy.diagonal(a, offset=0, axis1=0, axis2=1) 取对角线
a.diagonal()

# Return the imaginary part of the complex argument.
a.imag
a.max()
a.mean()
a.min()

# 返回非零的索引列表
a.nonzero()

# 原理同argpritition
np.partition(np.array([9,8,17,16,5,24]), 0) # [ 5,  8, 17, 16,  9, 24]

# numpy.prod(a, axis=None, dtype=None, out=None, keepdims=<class 'numpy._globals._NoValue'>)
# 返回类乘结果，cumprod返回的是每个元素的类乘结果列表
a.prod(axis=0)

# numpy.ptp(a, axis=None, out=None)
#  range of values(maximum - minimum) along an axis
a.ptp()

# numpy.put(a, index, v, mode='raise')
# replace specified elements of an array with given values.
a.put(23, 1)

# numpy.ravel(a, order='C')  # order : {‘C’,’F’, ‘A’, ‘K’}, optional
# Return a contiguous flattened array.
a.ravel()

# numpy.real(val)
# return the real part of complex argument.
a.real

# numpy.repeat(a, repeats, axis=None)
# repeat elements of an array.
a.repeat(2, axis=1)

a.reshape((6, 4))

# numpy.around(a, decimals=0, out=None)
# evenly round to the given number of decimals
a.round()

# numpy.searchsorted(a, v, side='left', sorter=None)
# find indices where elements should be inserted to maintain order.
np.searchsorted(np.sort(a,axis=None), 5)

np.sort(a,axis=None)

# remove single-dimensional entries from the shape of an array.
a.squeeze()

a.std()

a.sum()

# np.swapaxes(a, axis1, axis2)
a.swapaxes(0, 1)

# numpy.take(a, indices, axis=None, out=None, mode='raise')
# take elements from an array along an axis.
a.take([[1, 2],[3, 4]])
a.take(23)
np.eye(3)

# numpy.trace(a, offset=0, axis1=0, axis2=1, dtype=None, out=None
a.trace()

a.transpose()

a.var()

[[24 23 22 21 20 19]
 [18 17 16 15 14 13]
 [12 11 10  9  8  7]
 [ 6  5  4  3  2  1]]


47.916666666666664

> <span style="color:red">注：</span>　`argpartition`与`partition`,前者返回的索引，后者返回的值，执行原理相同．

In [ ]:
# 找出最终排序（升序）的，排在第2(0开始,2就是第三小的值)位的索引值拿出来，
# 将其他元素依次与第三小的值比较，如果比第三小的值小，就把相应值的索引放在左边，
# 如果大就放右边，最终返回一个索引列表．

# 如找出最小值所在的索引位置(即５的索引位置)
np.argpartition(np.array([9,8,17,16,5,24]), 0)[0] # 4
# 如找出第三小的值所在的索引位置(即９的索引位置)
np.argpartition(np.array([9,8,17,16,5,24]), 2)[2] # 0
# 如找出最大值所在的索引位置(即24的索引)
np.argpartition(np.array([9,8,17,16,5,24]), -1)[-1] # 5
# 如找出第２到第４小的值所在的索引位置(即8,9,16的索引)
np.argpartition(np.array([9,8,17,16,5,24]), (1,4))[1:4] # [1,0,3]

# 下面看一下第三小值(9)的完整返回值
li = np.argpartition(np.array([9,8,17,16,5,24]), 2) # [4, 1, 0, 3, 2, 5]
print(li) # [4, 1, 0, 3, 2, 5]
# 比９小的索引列表是
li[0:2] # [4, 1]
# 比９大的索引列表是
li[2+1:] # [3, 2, 5]

### 1.1.3 Array conversion
---

<table border="1" class="longtable docutils">
<colgroup>
<col width="10%" />
<col width="90%" />
</colgroup>
<tbody valign="top">
<tr class="row-odd"><td>ndarray.item(*args)</td>
<td>Copy an element of an array to a standard Python scalar and return it.</td>
</tr>
<tr class="row-even"><td>ndarray.tolist()</td>
<td>Return the array as a (possibly nested) list.</td>
</tr>
<tr class="row-odd"><td>ndarray.itemset(*args)</td>
<td>Insert scalar into an array (scalar is cast to array’s dtype, if possible)</td>
</tr>
<tr class="row-even"><td>ndarray.tostring([order])</td>
<td>Construct Python bytes containing the raw data bytes in the array.</td>
</tr>
<tr class="row-odd"><td>ndarray.tobytes([order])</td>
<td>Construct Python bytes containing the raw data bytes in the array.</td>
</tr>
<tr class="row-even"><td>ndarray.tofile(fid[,&nbsp;sep,&nbsp;format])</td>
<td>Write array to a file as text or binary (default).</td>
</tr>
<tr class="row-odd"><td>ndarray.dump(file)</td>
<td>Dump a pickle of the array to the specified file.</td>
</tr>
<tr class="row-even"><td>ndarray.dumps()</td>
<td>Returns the pickle of the array as a string.</td>
</tr>
<tr class="row-odd"><td>ndarray.astype(dtype[,&nbsp;order,&nbsp;casting,&nbsp;…])</td>
<td>Copy of the array, cast to a specified type.</td>
</tr>
<tr class="row-even"><td>ndarray.byteswap([inplace])</td>
<td>Swap the bytes of the array elements</td>
</tr>
<tr class="row-odd"><td>ndarray.copy([order])</td>
<td>Return a copy of the array.</td>
</tr>
<tr class="row-even"><td>ndarray.view([dtype,&nbsp;type])</td>
<td>New view of array with the same data.</td>
</tr>
<tr class="row-odd"><td>ndarray.getfield(dtype[,&nbsp;offset])</td>
<td>Returns a field of the given array as a certain type.</td>
</tr>
<tr class="row-even"><td>ndarray.setflags([write,&nbsp;align,&nbsp;uic])</td>
<td>Set array flags WRITEABLE, ALIGNED, (WRITEBACKIFCOPY and UPDATEIFCOPY), respectively.</td>
</tr>
<tr class="row-odd"><td>ndarray.fill(value)</td>
<td>Fill the array with a scalar value.</td>
</tr>
</tbody>
</table>



### 1.1.4 Shape manipulation
---

<table border="1" class="longtable docutils">
<colgroup>
<col width="10%" />
<col width="90%" />
</colgroup>
<tbody valign="top">
<tr class="row-odd"><td>ndarray.reshape(shape[,&nbsp;order])</td>
<td>Returns an array containing the same data with a new shape.</td>
</tr>
<tr class="row-even"><td>ndarray.resize(new_shape[,&nbsp;refcheck])</td>
<td>Change shape and size of array in-place.</td>
</tr>
<tr class="row-odd"><td>ndarray.transpose(*axes)</td>
<td>Returns a view of the array with axes transposed.</td>
</tr>
<tr class="row-even"><td>ndarray.swapaxes(axis1,&nbsp;axis2)</td>
<td>Return a view of the array with <em class="xref py py-obj">axis1</em> and <em class="xref py py-obj">axis2</em> interchanged.</td>
</tr>
<tr class="row-odd"><td>ndarray.flatten([order])</td>
<td>Return a copy of the array collapsed into one dimension.</td>
</tr>
<tr class="row-even"><td>ndarray.ravel([order])</td>
<td>Return a flattened array.</td>
</tr>
<tr class="row-odd"><td>ndarray.squeeze([axis])</td>
<td>Remove single-dimensional entries from the shape of <em class="xref py py-obj">a</em>.</td>
</tr>
</tbody>
</table>

### 1.1.5 Item selection and manipulation
---

<table border="1" class="longtable docutils">
<colgroup>
<col width="10%" />
<col width="90%" />
</colgroup>
<tbody valign="top">
<tr class="row-odd"><td>ndarray.take(indices[,&nbsp;axis,&nbsp;out,&nbsp;mode])</td>
<td>Return an array formed from the elements of <em class="xref py py-obj">a</em> at the given indices.</td>
</tr>
<tr class="row-even"><td>ndarray.put(indices,&nbsp;values[,&nbsp;mode])</td>
<td>Set <code class="docutils literal"><span class="pre">a.flat[n]</span> <span class="pre">=</span> <span class="pre">values[n]</span></code> for all <em class="xref py py-obj">n</em> in indices.</td>
</tr>
<tr class="row-odd"><td>ndarray.repeat(repeats[,&nbsp;axis])</td>
<td>Repeat elements of an array.</td>
</tr>
<tr class="row-even"><td>ndarray.choose(choices[,&nbsp;out,&nbsp;mode])</td>
<td>Use an index array to construct a new array from a set of choices.</td>
</tr>
<tr class="row-odd"><td>ndarray.sort([axis,&nbsp;kind,&nbsp;order])</td>
<td>Sort an array, in-place.</td>
</tr>
<tr class="row-even"><td>ndarray.argsort([axis,&nbsp;kind,&nbsp;order])</td>
<td>Returns the indices that would sort this array.</td>
</tr>
<tr class="row-odd"><td>ndarray.partition(kth[,&nbsp;axis,&nbsp;kind,&nbsp;order])</td>
<td>Rearranges the elements in the array in such a way that value of the element in kth position is in the position it would be in a sorted array.</td>
</tr>
<tr class="row-even"><td>ndarray.argpartition(kth[,&nbsp;axis,&nbsp;kind,&nbsp;order])</td>
<td>Returns the indices that would partition this array.</td>
</tr>
<tr class="row-odd"><td>ndarray.searchsorted(v[,&nbsp;side,&nbsp;sorter])</td>
<td>Find indices where elements of v should be inserted in a to maintain order.</td>
</tr>
<tr class="row-even"><td>ndarray.nonzero()</td>
<td>Return the indices of the elements that are non-zero.</td>
</tr>
<tr class="row-odd"><td>ndarray.compress(condition[,&nbsp;axis,&nbsp;out])</td>
<td>Return selected slices of this array along given axis.</td>
</tr>
<tr class="row-even"><td>ndarray.diagonal([offset,&nbsp;axis1,&nbsp;axis2])</td>
<td>Return specified diagonals.</td>
</tr>
</tbody>
</table>

### 1.1.6 Calculation
---

<table border="1" class="longtable docutils">
<colgroup>
<col width="10%" />
<col width="90%" />
</colgroup>
<tbody valign="top">
<tr class="row-odd"><td>ndarray.argmax([axis,&nbsp;out])</td>
<td>Return indices of the maximum values along the given axis.</td>
</tr>
<tr class="row-even"><td>ndarray.min([axis,&nbsp;out,&nbsp;keepdims])</td>
<td>Return the minimum along a given axis.</td>
</tr>
<tr class="row-odd"><td>ndarray.argmin([axis,&nbsp;out])</td>
<td>Return indices of the minimum values along the given axis of <em class="xref py py-obj">a</em>.</td>
</tr>
<tr class="row-even"><td>ndarray.ptp([axis,&nbsp;out])</td>
<td>Peak to peak (maximum - minimum) value along a given axis.</td>
</tr>
<tr class="row-odd"><td>ndarray.clip([min,&nbsp;max,&nbsp;out])</td>
<td>Return an array whose values are limited to <code class="docutils literal"><span class="pre">[min,</span> <span class="pre">max]</span></code>.</td>
</tr>
<tr class="row-even"><td>ndarray.conj()</td>
<td>Complex-conjugate all elements.</td>
</tr>
<tr class="row-odd"><td>ndarray.round([decimals,&nbsp;out])</td>
<td>Return <em class="xref py py-obj">a</em> with each element rounded to the given number of decimals.</td>
</tr>
<tr class="row-even"><td>ndarray.trace([offset,&nbsp;axis1,&nbsp;axis2,&nbsp;dtype,&nbsp;out])</td>
<td>Return the sum along diagonals of the array.</td>
</tr>
<tr class="row-odd"><td>ndarray.sum([axis,&nbsp;dtype,&nbsp;out,&nbsp;keepdims])</td>
<td>Return the sum of the array elements over the given axis.</td>
</tr>
<tr class="row-even"><td>ndarray.cumsum([axis,&nbsp;dtype,&nbsp;out])</td>
<td>Return the cumulative sum of the elements along the given axis.</td>
</tr>
<tr class="row-odd"><td>ndarray.mean([axis,&nbsp;dtype,&nbsp;out,&nbsp;keepdims])</td>
<td>Returns the average of the array elements along given axis.</td>
</tr>
<tr class="row-even"><td>ndarray.var([axis,&nbsp;dtype,&nbsp;out,&nbsp;ddof,&nbsp;keepdims])</td>
<td>Returns the variance of the array elements, along given axis.</td>
</tr>
<tr class="row-odd"><td>ndarray.std([axis,&nbsp;dtype,&nbsp;out,&nbsp;ddof,&nbsp;keepdims])</td>
<td>Returns the standard deviation of the array elements along given axis.</td>
</tr>
<tr class="row-even"><td>ndarray.prod([axis,&nbsp;dtype,&nbsp;out,&nbsp;keepdims])</td>
<td>Return the product of the array elements over the given axis</td>
</tr>
<tr class="row-odd"><td>ndarray.cumprod([axis,&nbsp;dtype,&nbsp;out])</td>
<td>Return the cumulative product of the elements along the given axis.</td>
</tr>
<tr class="row-even"><td>ndarray.all([axis,&nbsp;out,&nbsp;keepdims])</td>
<td>Returns True if all elements evaluate to True.</td>
</tr>
<tr class="row-odd"><td>ndarray.any([axis,&nbsp;out,&nbsp;keepdims])</td>
<td>Returns True if any of the elements of <em class="xref py py-obj">a</em> evaluate to True.</td>
</tr>
</tbody>
</table>

## 1.2 Arithmetic, matrix multiplication, and comparison operations
---

## 1.3 Special methods
---

## 1.2 Scalars
---

In [97]:
x = np.array([2,9,8,17,16,5,24])
x[np.argpartition(x, 2)]

array([ 2,  5,  8, 17, 16,  9, 24])

In [79]:
a = np.array([3, 5, 2, 1])
np.partition(a, -2)

array([1, 2, 3, 5])

In [207]:
np.busday?

Object `np.busday` not found.


## 1.3 Data type objects(dtype)
---

## 1.4 Indexing
---

## 1.5
---